### ISSUE TITLE
add ability to specify different node names

### ISSUE THREAD

**Issue by zilkey** [zilkey/active_api#3]

**Comment by zilkey** [comment]
This is accomplished by the ability to specify different values for each element

**Comment by louisgillies** [comment]
This is OK for child nodes and elements but is it possible to change the name of the root node?
I have added a reader attribute in collection.rb called name which is set if the options[:as] is passed otherwise it defaults to node.to_s.pluralize as before.
There may be a way to do this using custom definition and builder subclasses but I couldn't work it out!

**Comment by cjk** [comment]
I second this. It's not always feasable to name an xml-element after it's (pluralized) class-name. Sometimes I want to create a collection of - say, text-elements, but the xml-element should be called "articles" and not "texts". How is this done? The :node parameter only accepts existing models.
